### ISSUE TITLE
Allow for empty "Asana assignee ID"

### ISSUE THREAD

**Issue by star26bsd** [Webtica/integration-for-elementor-forms-asana#1]
Tried to find out whether or not the "Asana assignee ID" is mandatory or not (whereas it is kind of obvious for Workspace ID and Project ID). Maybe the descriptive text next to this field could state whether or not this field is mandatory.

My use case would be to leave it empty, so that the Asana task has not an assignee set on creation of the task.

Thanks
Stephan

![Screenshot 2022-07-17 at 09 51 19 PM](https://user-images.githubusercontent.com/8288962/179422484-47e31e8d-68ed-439c-a051-2ce97ba74854.png)

**Comment by Webtica** [comment]
Currently the assignee needs to be mandatory. Will check if the API allows it.

**Comment by star26bsd** [comment]
I propose to make all mandatory fields recognizable (red star) and/or enforce fill-in on submit.

**Comment by star26bsd** [comment]
According to the docs I have found, the 'assignee' is not mandatory:

https://developers.asana.com/docs/create-a-task

`assignee string¦**null** | Gid of a user.`

Would be nice if the Plugin would respect that. This way, one can set up a workflow where tasks are unassigned (queue) and need to be triaged manually.

Thanks!

**Comment by Webtica** [comment]
This is now released in version PRO 1.1.0
