### ISSUE TITLE
Stable tag of 1.0.2 remains 1.0.1

### ISSUE THREAD

**Issue by star26bsd** [Webtica/integration-for-elementor-forms-asana#10]
I had to update manually to 1.0.2 and then Wordpress asked me if I want to update from 1.0.1 to 1.0.1. I guess the stable tag had been forgotten to be updated? Or somewhere else the info, that the new release is indeed 1.0.2 is missing.

**Comment by Webtica** [comment]
This should now be fixed. Thanks for posting.
