### ISSUE TITLE
Cannot get rid of custom field mapping entirely, always one present

### ISSUE THREAD

**Issue by star26bsd** [Webtica/integration-for-elementor-forms-asana#2]
For debugging purposes, I wanted to remove all "Asana Custom Field Mappings" - however, removing the second-last leaves one without an X option to remove it. That always leaves on mapping around. I guess there will be people without mappings, so being able to remove them all mind be also handy for non-debugging purposes.

Thanks
Stephan

![Screenshot 2022-07-17 at 09 55 04 PM](https://user-images.githubusercontent.com/8288962/179422635-b4c22954-6560-43e1-8342-d8ca572ea5b3.png)

**Comment by Webtica** [comment]
Hi @star26bsd,

This is now implemented in the next update released in a few hours. 1.0.2
Closing for now. If there is an issue you can reopen or make a new issue.
