### ISSUE TITLE
Allow due date to be set dynamically

### ISSUE THREAD

**Issue by star26bsd** [Webtica/integration-for-elementor-forms-asana#4]
In one use case, a form asks for a specific date then one could use to set the due date in Asana. Think of booking something.

Right now, the due date only accepts static entries in form of numbers. It would be nice if some future release could address making this field dynamic. Like a customer choses a date in the form with a date picker and that one is used in the field.

Thanks
Stephan

**Comment by Webtica** [comment]
This is now released in version PRO 1.1.0
